package com.pocketsteward.app.executor

import com.pocketsteward.app.data.db.FileRecord
import com.pocketsteward.app.data.db.FileRecordDao
import com.pocketsteward.app.data.db.MutationOperationType
import com.pocketsteward.app.data.db.MutationRecord
import com.pocketsteward.app.data.db.MutationRecordDao
import com.pocketsteward.app.data.db.MutationStatus
import com.pocketsteward.app.data.db.TaskRunDao
import com.pocketsteward.app.data.db.TaskRunStatus
import com.pocketsteward.app.data.db.UndoState
import com.pocketsteward.app.storage.FileMetadata
import com.pocketsteward.app.storage.FileRef
import com.pocketsteward.app.storage.FileRefJournalCodec
import com.pocketsteward.app.storage.MutationResult
import com.pocketsteward.app.storage.StorageAccessMode
import com.pocketsteward.app.storage.StorageGateway
import com.pocketsteward.app.storage.rawValue

data class UndoSummary(
    val taskRunId: Long,
    val undone: Int,
    val skipped: Int,
    val blocked: Int,
    val messages: List<String>,
) {
    val complete: Boolean get() = blocked == 0
}

/**
 * Replays committed mutations in reverse order. The inverse is derived from
 * the durable journal, never regenerated by a planner/model.
 */
class UndoExecutor(
    private val fileRecordDao: FileRecordDao,
    private val taskRunDao: TaskRunDao,
    private val mutationRecordDao: MutationRecordDao,
    private val gatewayFor: (StorageAccessMode) -> StorageGateway,
) {
    suspend fun undo(taskRunId: Long): UndoSummary {
        val task = taskRunDao.getById(taskRunId) ?: error("Unknown task run: $taskRunId")
        require(task.status == TaskRunStatus.COMPLETED || task.status == TaskRunStatus.FAILED) {
            "Task is not in an undoable state: ${task.status}"
        }
        val initialRecords = mutationRecordDao.getForTaskRunReverse(taskRunId)
        require(initialRecords.any { it.status == MutationStatus.COMMITTED && it.undoState == UndoState.AVAILABLE }) {
            "This task has no reversible committed changes."
        }

        val gateway = gatewayFor(task.storageAccessMode)
        taskRunDao.update(task.copy(status = TaskRunStatus.UNDOING))

        var undone = 0
        var skipped = 0
        var blocked = 0
        val messages = mutableListOf<String>()

        for (record in initialRecords) {
            if (record.status == MutationStatus.UNDONE || record.undoState == UndoState.UNDONE) {
                skipped++
                continue
            }
            if (record.status != MutationStatus.COMMITTED || record.undoState != UndoState.AVAILABLE) {
                skipped++
                continue
            }

            val pending = record.copy(
                undoState = UndoState.PENDING,
                undoAttemptedAt = System.currentTimeMillis(),
                undoError = null,
            )
            mutationRecordDao.update(pending)

            when (val result = undoOne(pending, gateway)) {
                is MutationResult.Success -> {
                    mutationRecordDao.update(
                        pending.copy(
                            status = MutationStatus.UNDONE,
                            undoState = UndoState.UNDONE,
                            undoError = null,
                        ),
                    )
                    reindexAfterUndo(pending, task.scopeRootRef, gateway)
                    undone++
                }

                is MutationResult.Failure -> {
                    mutationRecordDao.update(
                        pending.copy(
                            undoState = UndoState.BLOCKED,
                            undoError = result.reason,
                        ),
                    )
                    blocked++
                    messages += "${record.operationType}: ${result.reason}"
                }
            }
        }

        val now = System.currentTimeMillis()
        val latestTask = taskRunDao.getById(taskRunId) ?: task
        taskRunDao.update(
            latestTask.copy(
                status = if (blocked == 0) TaskRunStatus.UNDONE else TaskRunStatus.UNDO_PARTIAL,
                undoCompletedAt = if (blocked == 0) now else null,
                summary = buildString {
                    append(latestTask.summary.orEmpty())
                    if (isNotEmpty()) append(" · ")
                    append("Undo: $undone restored, $blocked blocked, $skipped skipped")
                },
            ),
        )

        return UndoSummary(taskRunId, undone, skipped, blocked, messages)
    }

    private suspend fun undoOne(record: MutationRecord, gateway: StorageGateway): MutationResult {
        val destinationAfter = record.destinationAfter?.let(FileRefJournalCodec::decode)
            ?: return MutationResult.Failure("Journal has no post-operation destination to undo.")

        return when (record.operationType) {
            MutationOperationType.CREATE_DIRECTORY -> gateway.removeEmptyDirectory(destinationAfter)
            MutationOperationType.MOVE,
            MutationOperationType.RENAME,
            MutationOperationType.TRASH,
            -> {
                val original = FileRefJournalCodec.decode(record.sourceBefore)
                val currentExists = gateway.exists(destinationAfter)
                val originalExists = gateway.exists(original)
                when {
                    originalExists -> MutationResult.Failure(
                        "Original location is occupied; refusing to overwrite it: ${original.rawValue()}",
                    )
                    !currentExists -> MutationResult.Failure(
                        "Expected current file is missing; cannot prove what should be restored: ${destinationAfter.rawValue()}",
                    )
                    else -> gateway.move(destinationAfter, original)
                }
            }
            MutationOperationType.COPY -> MutationResult.Failure("COPY undo is not implemented in V1.")
        }
    }

    private suspend fun reindexAfterUndo(record: MutationRecord, scopeRootRef: String, gateway: StorageGateway) {
        val destinationAfter = record.destinationAfter?.let(FileRefJournalCodec::decode) ?: return
        when (record.operationType) {
            MutationOperationType.CREATE_DIRECTORY -> {
                fileRecordDao.deleteByStableRef(destinationAfter.rawValue())
            }
            MutationOperationType.MOVE,
            MutationOperationType.RENAME,
            MutationOperationType.TRASH,
            -> {
                val restored = FileRefJournalCodec.decode(record.sourceBefore)
                fileRecordDao.deleteByStableRef(destinationAfter.rawValue())
                val meta = gateway.stat(restored)
                fileRecordDao.upsert(meta.toFileRecord(scopeRootRef, restored.parentRefOrNull()))
            }
            MutationOperationType.COPY -> Unit
        }
    }
}

private fun FileRef.parentRefOrNull(): FileRef? = when (this) {
    is FileRef.Direct -> absolutePath.substringBeforeLast('/', missingDelimiterValue = "")
        .takeIf { it.isNotBlank() }
        ?.let(FileRef::Direct)
    is FileRef.Saf -> null
}

private fun FileMetadata.toFileRecord(scopeRootRef: String, parent: FileRef?): FileRecord = FileRecord(
    stableRef = ref.rawValue(),
    scopeRootRef = scopeRootRef,
    displayName = displayName,
    extension = extension,
    mimeType = mimeType,
    absolutePathOrUri = ref.rawValue(),
    parentRef = parent?.rawValue(),
    sizeBytes = sizeBytes,
    createdAt = createdAtEpochMs,
    modifiedAt = modifiedAtEpochMs,
    lastScannedAt = System.currentTimeMillis(),
    isDirectory = isDirectory,
    isHidden = isHidden,
)
